apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ops-ingress
  labels:
    app.kubernetes.io/name: ops-portal
    app.kubernetes.io/part-of: indetechs-phase3
    app.kubernetes.io/component: frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: ops.indetechs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ops-frontend
                port:
                  number: 8080
