apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - app-config.yaml
  - database.yaml
  - backend.yaml
  - frontend.yaml
  - frontend-hpa.yaml
  - ingress.yaml
  - networkpolicy-allow-traefik.yaml

images:
  - name: docker.io/anik50/indetechs-ops-frontend
    newTag: v2
  - name: docker.io/anik50/indetechs-ops-backend
    newTag: v2
  - name: docker.io/anik50/indetechs-ops-database
    newTag: v2
