apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: app-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: database-pdb
  namespace: app-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: database

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: app-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
