apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-prod
  labels:
    environment: prod
